Autosave commit created on Fri May 10 13:14:25 PDT 2019.

diff --git a/scripts/agitate b/scripts/agitate
--- a/scripts/agitate
+++ b/scripts/agitate
@@ -53,17 +53,33 @@ if [ "x${arg}x" = "xx" ] || [ "x${arg}x" = "x-hx" ] || [ "x${arg}x" = "x--helpx"
     echo "Example usage: "
     echo ""
     echo "    cd local_path_to/top_of_my_git_repo"
-    echo "    autosave_continuously.sh ubuntu@devserver.aws.com:remote_path_to/top_of_my_git_repo"
+    echo "    agitate ubuntu@devserver.aws.com:remote_path_to/top_of_my_git_repo"
+    echo ""
+    echo "You may omit the last component of the remote path, since it can be inferred"
+    echo "from the local path."
     exit 0
 fi
 
 REMOTE_USER=`echo "${arg}"  | awk -F'\(@\|\:\)' '{print $1}'`
 REMOTE_HOST=`echo "${arg}"  | awk -F'\(@\|\:\)' '{print $2}'`
 REMOTE_WORK_DIR=`echo "${arg}"  | awk -F'\(@\|\:\)' '{print $3}'`
+REPO_DIR=`basename ${PWD}`
+INFERRED=0
 
-if [ "x`basename ${REMOTE_WORK_DIR}`x" != "x`basename ${PWD}`x" ]; then
-    echo "ERROR:  Remote workdir basename `basename ${REMOTE_WORK_DIR}` is different from local workdir basename `basename ${PWD}`."
-    echo ""
+if [ "x${REMOTE_WORK_DIR}x" == "xx" ]; then
+    REMOTE_WORK_DIR="${REPO_DIR}"
+    INFERRED=1
+elif [ "x`basename ${REMOTE_WORK_DIR}`x" != "x${REPO_DIR}x" ]; then
+    REMOTE_WORK_DIR="${REMOTE_WORK_DIR}/${REPO_DIR}"
+    INFERRED=1
+fi
+
+if [ ${INFERRED} == 1 ]; then
+    echo "INFO:  Inferred remote path: '${REMOTE_USER}@${REMOTE_HOST}:${REMOTE_WORK_DIR}'."
+fi
+
+if ! ssh ${REMOTE_USER}@${REMOTE_HOST} test -d "${REMOTE_WORK_DIR}/.git";  then
+    echo "ERROR:  Cannot access remote dir '${REMOTE_USER}@${REMOTE_HOST}:${REMOTE_WORK_DIR}/.git'."
     $0 --help
     exit 1
 fi
